# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
#
# This is the configuration file for Pythia, a tool to identify Delphi vtables.

profiles:

    delphi_2xxx:
        # What boundary are vtables aligned to (should match architecture)
        align: 4

        # How far is it from vmtSelfPtr to the start of user functions?
        distance: 0x4C

    delphi_modern_x86:
        align: 4
        distance: 0x58

known_guids:
    "00000000-0000-0000-c000-000000000046": IUnknown
